export const GET_DOGS = 'GET_DOGS';
export const GET_DOG = "GET_DOG";
export const ADD_DOG = "ADD_DOG";
export const SRC_DOG = "SRC_DOG";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const FILTER_DOGS =  "FILTER_DOGS";
export const SORT_DOGS =  "SORT_DOGS";
export const SET_CURRENT_PAGE =  "SET_CURRENT_PAGE";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const SORT_DOGS_BY_NAME_ASC = 'SORT_DOGS_BY_NAME_ASC';
export const SORT_DOGS_BY_NAME_DESC = 'SORT_DOGS_BY_NAME_DESC';
export const FILTER_DOGS_BY_WEIGHT_ASC = 'FILTER_DOGS_BY_WEIGHT_ASC';
export const FILTER_DOGS_BY_WEIGHT_DESC = 'FILTER_DOGS_BY_WEIGHT_DESC';
export const  FILTER_DOGS_BY_TEMPERAMENT = 'FILTER_DOGS_BY_TEMPERAMENT';
export const FILTER_DOGS_BY_ORIGIN = 'FILTER_DOGS_BY_ORIGIN'



